# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Test and Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        pip install flake8

    - name: Run flake8
      run: |
        & "${env:pythonLocation}\Scripts\flake8" . --count --select=E9,F63,F7,F82 --show-source --statistics
        & "${env:pythonLocation}\Scripts\flake8" . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: pwsh
      env:
        pythonLocation: 'C:\hostedtoolcache\windows\Python\3.10.11\x64'

    - name: Test with pytest
      run: |
        python -m pytest --verbose
        coverage run -m pytest
        coverage xml -i
      env:
        pythonLocation: 'C:\hostedtoolcache\windows\Python\3.10.11\x64'

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./coverage

  coverage:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install coverage tool
      run: pip install coverage

    - name: Download coverage results from the test job
      uses: actions/download-artifact@v2
      with:
        name: coverage

    - name: Display coverage report
      run: coverage report
